# Generated by Django 5.1.3 on 2026-03-08 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrigerant', models.CharField(default='Ammonia', max_length=50)),
                ('evaporation_temperature_c', models.FloatField(help_text='Te (°C)')),
                ('condensing_temperature_c', models.FloatField(help_text='Tc (°C)')),
                ('evaporation_pressure_bar', models.FloatField(blank=True, null=True)),
                ('condensing_pressure_bar', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
